### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by garethnrh** [VladimirMikulic/visum#2]
Hi 

following the steps outlined leads to the following output:

===============================================================
gareth@kali:~$ git clone https://github.com/VladimirMikulic/visum.git
Cloning into 'visum'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 30 (delta 7), reused 30 (delta 7), pack-reused 0
Unpacking objects: 100% (30/30), 3.83 MiB | 1.17 MiB/s, done.
gareth@kali:~$ chmod +x visum/install.sh
gareth@kali:~$ ./visum/install.sh
Installing Visum...
Dependencies satisfied.
[sudo] password for gareth: 
cp: cannot stat './scripts': No such file or directory
cp: cannot stat './media': No such file or directory
cp: cannot stat './visum.desktop': No such file or directory

Done! Enjoy Visum :)
gareth@kali:~$ 

==============================================================

Program will not then run.
"cp: cannot stat" normally relates to paths with spaces or special characters but cannot see how this applies in this case.

I am not a programmer and only have a tenuous grasp of the command line and linux file systems.

regards

Gareth

**Comment by VladimirMikulic** [comment]
Thanks, @garethnrh! I've resolved the issue. Let me know how it works for you.
