### ISSUE TITLE
file not found errors

### ISSUE THREAD

**Issue by ntaraujo** [VladimirMikulic/visum#4]
Neither Microsoft nor Google visualizer worked. Made a normal installation and opened some files under my home directory. Looks like they can't access the files.

I'm on Pop OS 20.04 LTS, and Chrome 92.0.4515.131 (Official Build) (64-bit)

Follows 2 prints using Microsoft and 1 with Google. Each of them with the console log.

### File not found

![image](https://user-images.githubusercontent.com/66187211/128519141-92d321a6-6264-4bbd-aa5f-c15017e658d1.png)

```
filenotfound.htm?llcc=pt-BR&hid=2aac64e7-0f2e-4b6a-a189-b1c96126a54b:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
loadScript @ filenotfound.htm?llcc=pt-BR&hid=2aac64e7-0f2e-4b6a-a189-b1c96126a54b:1
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 ()
```

### An error has occurred

![image](https://user-images.githubusercontent.com/66187211/128519180-0e4557e1-fc21-4dff-ad13-9cc703caf520.png)

```
errorpage.htm?llcc=pt-BR&hid=ee2e7caf-470b-4d47-ad4e-2ce80ed4f592:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
loadScript @ errorpage.htm?llcc=pt-BR&hid=ee2e7caf-470b-4d47-ad4e-2ce80ed4f592:1
```

### No preview available

![image](https://user-images.githubusercontent.com/66187211/128519208-aaf97c20-851e-4552-baa1-dba5cbfb42ed.png)

```
viewer:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
i:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by VladimirMikulic** [comment]
Hi @ntaraujo. I appreciate the report. Have you run [this](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key)? Thanks.

**Comment by ntaraujo** [comment]
Oh, I see. Thank you.
