### ISSUE TITLE
Cant work on Arch

### ISSUE THREAD

**Issue by fecet** [VladimirMikulic/visum#5]
Finding this repository is really a surprise to me, but sadly it cant work on my linux. I try to open with Visum in thunar and try to use Firefox and msedge as default browser, both didn't work. When I use Firefox, there is nothing open, while msedge will download my local file. 

I also try to use cli and got a 'x-www-browser not found' error.

Btw, msedge has a new feature that can use office view to open office file instead of download it, but i seems not work on linux.(I disable it while testing visum), maybe this feature can be helpful for this project.

**Comment by VladimirMikulic** [comment]
Interesting issue @fecet. Thanks for the report.
Could you please try set up from [this](https://unix.stackexchange.com/questions/584478/how-to-add-browser-to-update-alternatives) link?

**Comment by fecet** [comment]
Thank you for your prompt response. Seems update-alternatives is a command only for Debian, doesn't work for me.

**Comment by VladimirMikulic** [comment]
@fecet `x-www-browser` command picks your default browser to open a file with.
Since it's not found for you, I guess it doesn't come installed on Arch Linux.

Could you try replacing it with your browser command?
(i.e. `firefox` or `google-chrome`)

**Comment by fecet** [comment]
I replace it to `firefox` and `microsoft-edge-beta`, then visum will upload file and open browser as expected, but the page is 
```
File not found
The URL of the original file is not valid or the document is not publicly accessible.
Verify the URL is correct, then contact the document owner.
```

**Comment by VladimirMikulic** [comment]
@fecet have you read step 1 in the installation section? :)
https://github.com/VladimirMikulic/visum#package-installation

**Comment by fecet** [comment]
Sorry I still not quite familiar with SSH. I already have a ssh key in https://github.com/settings/keys, and I can use it to clone repository, it's possible I still miss something and have to regenerate one?

**Comment by VladimirMikulic** [comment]
@fecet no worries! You just need to generate an SSH key locally which the program will use.
It's not exclusive to GitHub, but GitHub has the best guides so I posted it.

If you follow the 4 steps here, you should be good to go:
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key

**Comment by fecet** [comment]
Thanks, now I can use visum in GUI by "open with visum"! But "visum <path>" behavior remain the same.

**Comment by VladimirMikulic** [comment]
So, visum's CLI doesn't work for you?

**Comment by fecet** [comment]
Yes, but just using `xdg-open` is good enough for me. If you would like to deep dive this issue and need me to confirm something, just let me know. Thanks again for your reply and great work.😃

**Comment by VladimirMikulic** [comment]
@fecet alright then! Enjoy visum and I'll hopefully soon be able to fix CLI :)
